rewrite fstime on n-api
l0gd0g/fstime pull request #3
Opened 2019-11-01 14:18 UTC by Velmisov

2019-11-01 14:45 UTC, CheerlessCloud requested changes

2019-11-01 14:45 UTC, CheerlessCloud commented on binding.gyp
> +      	  "sources": [ "src/fstime-napi.cc" ]
А зачем так? Почему не поменять содержимое `src/fstime.cc`? Ну или как минимум удалите старый код.

2019-11-01 14:45 UTC, CheerlessCloud commented on src/fstime-napi.cc
> +    if (status != napi_ok) return NULL;
Ох... Смущает меня вот это везде `return NULL`. Как насчёт попробовать сделать нормальную обработку ошибок? Ну или хотя бы стандартных кейсов.

2019-11-01 14:45 UTC, CheerlessCloud commented on src/fstime-napi.cc
> +    struct stat sb;
Что есть `sb`? Давайте развернём название переменной.

2019-11-01 14:45 UTC, CheerlessCloud commented on src/fstime-napi.cc
> +    if (setProperty(env, stats, "uid", sb.st_uid) != napi_ok) return NULL;
Да нам вроде бы не нужна эта информация, не? Как было в старом коде? Если не пробрасывалось то предлагается и тут не пробрасывать.

2019-11-01 14:45 UTC, CheerlessCloud commented on src/fstime-napi.cc
> +    fileNameSize += 1;
А? Зачем так? О_О

2019-11-01 14:45 UTC, CheerlessCloud commented on src/fstime-napi.cc
> +    char fileName[fileNameSize];
Надо будет это с русскими буквами в пути протестить 😉

2019-11-01 14:45 UTC, CheerlessCloud commented on src/fstime-napi.cc
> +    if (utimensat(AT_FDCWD, fileName, ts, AT_SYMLINK_NOFOLLOW) < 0) {
А у нас там и было такое поведение для симлинков?

2019-11-01 14:49 UTC, Velmisov commented on src/fstime-napi.cc
> +    if (setProperty(env, stats, "uid", sb.st_uid) != napi_ok) return NULL;
было

2019-11-01 14:50 UTC, Velmisov commented on src/fstime-napi.cc
> +    fileNameSize += 1;
в сях +1 байт на конец строки всегда резервируется

2019-11-01 14:50 UTC, Velmisov commented on src/fstime-napi.cc
> +    if (utimensat(AT_FDCWD, fileName, ts, AT_SYMLINK_NOFOLLOW) < 0) {
да

2019-11-01 14:51 UTC, Velmisov commented on src/fstime-napi.cc
> +    struct stat sb;
https://linux.die.net/man/2/lstat

2019-11-01 14:51 UTC, Velmisov commented on src/fstime-napi.cc
> +    char fileName[fileNameSize];
у нас же вроде нет русских букв?

2019-11-01 14:54 UTC, CheerlessCloud commented on src/fstime-napi.cc
> +    fileNameSize += 1;
Сорян, думал napi само пробросит.

2019-11-01 14:56 UTC, CheerlessCloud commented on src/fstime-napi.cc
> +    char fileName[fileNameSize];
Мы тут повспоминали и думаем что могут быть, например в названиях html файлов.

2019-11-01 14:57 UTC, Velmisov commented on src/fstime-napi.cc
> +    char fileName[fileNameSize];
ну переделаю на utf16 тогда

2019-11-02 10:03 UTC, Velmisov commented on src/fstime-napi.cc
> +    char fileName[fileNameSize];
И так работает

2019-11-05 08:49 UTC, CheerlessCloud requested changes

2019-11-05 08:49 UTC, CheerlessCloud commented on src/fstime.cc
> +napi_status status;
А зачем вот так вот?)

2019-11-05 09:00 UTC, Velmisov commented on src/fstime.cc
> +napi_status status;
Ну она везде используется - в разных областях видимости. Независимая. На каждую операцию создавать новую нет смысла, так как суть у неё одна

2019-11-05 09:11 UTC, CheerlessCloud commented on src/fstime.cc
> +napi_status status;
Ну ты же понимаешь что это почти глобальная переменная?

2019-11-05 09:18 UTC, Velmisov commented on src/fstime.cc
> +napi_status status;
Не почти

2019-11-05 13:55 UTC, Velmisov commented on src/fstime.cc
> +napi_status status;
Убрал её

2019-11-05 14:38 UTC, CheerlessCloud approved these changes

2019-11-07 09:23 UTC, merged